#!/usr/bin/env bash
# Script that display information about subdomains

display ()
{
	dig "$2"."$1" | awk '/ANSWER SECTION:/{getline; print "The subdomain "$2" is a "$4" record and points to "$5}'
}
for sub in "www" "lb-01" "web-01" "web-02"; do
	if [ -z "$2" ] || [ "$2" == "$sub" ]; then
		display "$1" "$sub"
	fi
done
