#!/usr/bin/env bash
# Modify Nginx to listen on port 80 and stop the service
sudo sed -i '/^[^#]*listen/s/[0-9]\+;/80;/' /etc/nginx/sites-available/default
service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
